---

steps:
- name: backend
  image: ubuntu
  commands:
  - echo $(date)
  - sleep 30
  - echo ciao
  - echo "ciao" > merda

- name: frontend
  image: alpine/git
  commands:
  - pwd
  - ls -la
  - cat merda
  - cat README.md
