---

steps:
- name: go
  image: golang:1.14.2
  commands:
  - go version
# - name: backend
#   image: ubuntu
#   commands:
#   - echo $(date)
#   - sleep 2
#   - echo ciao
#   - echo "ciao" > merda

- name: frontend
  image: alpine/git
  commands:
  - pwd
  - ls -la
  - cat merda
  - cat README.md
