---
name: daje

steps:
- name: backend
  image: ubuntu
  commands:
  - echo $(date)
  - echo ciao
  - echo "ciao" > merda

- name: frontend
  image: alpine/git
  commands:
  - pwd
  - ls -la
  - cat .quad.yml
